int   playback = 0;
int   record = 0;
int   *playback_ints;
int   *playback_errnos;
int   *playback_errnos_start;
short *playback_shorts;
short *playback_shorts_start;
char  *playback_strings;
char  *playback_data;
char  *playback_sched;
int   *playback_ints_start;
char  *playback_strings_start;
char  *playback_data_start;
char  *playback_sched_start;
int   *playback_ei;
char  *playback_es;
int   *playback_ei_start;
char  *playback_es_start;
int   rrecord;
int   rplayback;
int   recOpt;
