/*
* XpilotStudio, the XPilot Map Editor for Windows 95/98/NT.  Copyright (C) 2000 by
*
*      Jarrod L. Miller           <jlmiller@ctitech.com>
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*
* See the file COPYRIGHT.TXT for current copyright information.
*
*/
/*DEFAULT SETTINGS - INCLUDES ALL SERVER OPTIONS EXCEPT MAPDATA
THESE ARE ORDERED IN THE SAME ORDER AS THE OPTIONS HELP FROM XPILOT
FOR EASE OF UPDATING WITH EACH NEW XPILOT VERSION*/
int                      num_default_settings=NUMPREFS;
charlie                  default_settings[NUMPREFS] = {
	{ "gravity","-0.14" },
	{ "shipmass","20.0" },
	{ "shotmass","0.1" },
	{ "shotspeed","21.0" },
	{ "shotlife","60" },
	{ "firerepeatrate","2" },
	{ "maxplayershots","256" },
	{ "shotsgravity","yes" },
	{ "idlerun","no" },
	{ "noquit","no" },
	{ "mapwidth","3500" },
	{ "mapheight","3500" },
	{ "mapname","New Map" },
	{ "mapauthor","Your Name" },
	{ "contactport","15345" },
	{ "allowplayercrashes","yes" },
	{ "allowplayerbounces","yes" },
	{ "allowplayerkilling","yes" },
	{ "allowshields","yes" },
	{ "playerstartsshielded","yes" },
	{ "shotswallbounce","no" },
	{ "ballswallbounce","yes" },
	{ "mineswallbounce","no" },
	{ "itemswallbounce","yes" },
	{ "missileswallbounce","no" },
	{ "sparkswallbounce","no" },
	{ "debriswallbounce","no" },
	{ "cloakedexhaust","yes" },
	{ "cloakedshield","yes" },
	{ "maxobjectwallbouncespeed","40" },
	{ "maxshieldedwallbouncespeed","50" },
	{ "maxunshieldedwallbouncespeed","20" },
	{ "playerwallbouncebrakefactor","0.89" },
	{ "objectwallbouncebrakefactor","0.95" },
	{ "objectwallbouncelifefactor","0.80" },
	{ "wallbouncefueldrainmult","1.0" },
	{ "wallbouncedestroyitemprob","0.0" },
	{ "reporttometaserver","yes" },
	{ "searchdomainforxpilot", "yes"},
	{ "denyhosts","\0" },
	{ "limitedvisibility","no" },
	{ "minvisibilitydistance","0.0" },
	{ "maxvisibilitydistance","0.0" },
	{ "limitedlives","no" },
	{ "worldlives","0" },
	{ "reset","yes" },
	{ "resetonhuman","no" },
	{ "teamplay","no" },
	{ "teamcannons","no" },
	{ "teamfuel","no" },
	{ "cannonsmartness","1" },
	{ "cannonsuseitems","no" },
	{ "keepshots","no" },
	{ "teamimmunity","yes" },
	{ "ecmsreprogrammines","yes" },
	{ "targetkillteam","no" },
	{ "targetteamcollision","yes" },
	{ "targetsync","no" },
	{ "treasurekillteam","no" },
	{ "treasurecollisiondestroys","yes" },
	{ "treasurecollisionmaykill","no" },
	{ "wreckagecollisionmaykill","no" },
	{ "ignore20maxfps","yes" },
	{ "oneplayeronly","no" },
	{ "timing","no" },
	{ "edgewrap","no" },
	{ "gravitypoint","0,0" },
	{ "gravityangle","90" },
	{ "gravitypointsource","no" },
	{ "gravityclockwise","no" },
	{ "gravityanticlockwise","no" },
	{ "gravityvisible","yes" },
	{ "wormholevisible","yes" },
	{ "itemconcentratorvisible","yes" },
	{ "wormtime","0" },
	{ "defaultsfilename","\0"},
	{ "framespersecond","14" },
	{ "allowsmartmissiles","yes" },
	{ "allowheatseekers","yes" },
	{ "allowtorpedoes","yes" },
	{ "allownukes","no" },
	{ "allowclusters","no" },
	{ "allowmodifiers","no" },
	{ "allowlasermodifiers","no" },
	{ "allowshipshapes","yes" },
	{ "playersonradar","yes" },
	{ "missilesonradar","yes" },
	{ "minesonradar","no" },
	{ "nukesonradar","yes" },
	{ "treasuresonradar","no" },
	{ "distinguishmissiles","yes" },
	{ "maxmissilesperpack","4" },
	{ "maxminesperpack","2" },
	{ "identifymines","yes" },
	{ "shieldeditempickup","no" },
	{ "shieldedmining","no" },
	{ "laserisstungun","no" },
	{ "nukeminsmarts","7" },
	{ "nukeminmines","4" },
	{ "nukeclusterdamage","1.0" },
	{ "minefusetime","0.0" },
	{ "minelife","0" },
	{ "missilelife","0" },
	{ "baseminerange","0" },
	{ "shotkillscoremult","1.0" },
	{ "torpedokillscoremult","1.0" },
	{ "smartkillscoremult","1.0" },
	{ "heatkillscoremult","1.0" },
	{ "clusterkillscoremult","1.0" },
	{ "laserkillscoremult","1.0" },
	{ "tankkillscoremult","0.44" },
	{ "runoverkillscoremult","0.33" },
	{ "ballkillscoremult","1.0" },
	{ "explosionkillscoremult","0.33" },
	{ "shovekillscoremult","0.5" },
	{ "crashscoremult","0.33" },
	{ "minescoremult","0.17" },
	{ "movingitemprob","0.2" },
	{ "dropitemonkillprob","0.5" },
	{ "detonateitemonkillprob","0.5" },
	{ "destroyitemincollisionprob","0.0" },
	{ "itemprobmult","1.0" },
	{ "cannonitemprobmult","1.0" },
	{ "maxitemdensity","0.00012" },
	{ "itemconcentratorradius","10" },
	{ "itemconcentratorprob","1.0" },
	{ "rogueheatprob","1.0" },
	{ "roguemineprob","1.0" },
	{ "itemenergypackprob","1e-9" },
	{ "itemtankprob","1e-9" },
	{ "itemecmprob","1e-9" },
	{ "itemarmorprob","1e-9" },
	{ "itemmineprob","1e-9" },
	{ "itemmissileprob","1e-9" },
	{ "itemcloakprob","1e-9" },
	{ "itemsensorprob","1e-9" },
	{ "itemwideangleprob","1e-9" },
	{ "itemrearshotprob","1e-9" },
	{ "itemafterburnerprob","1e-9" },
	{ "itemtransporterprob","1e-9" },
	{ "itemmirrorprob","1e-9" },
	{ "itemdeflectorprob","1e-9" },
	{ "itemhyperjumpprob","1e-9" },
	{ "itemphasingprob","1e-9" },
	{ "itemlaserprob","1e-9" },
	{ "itememergencythrustprob","1e-9" },
	{ "itemtractorbeamprob","1e-9" },
	{ "itemautopilotprob","1e-9" },
	{ "itememergencyshieldprob","1e-9" },
	{ "initialfuel","1000" },
	{ "initialtanks","0" },
	{ "initialarmor","0" },
	{ "initialecms","0" },
	{ "initialmines","0" },
	{ "initialmissiles","0" },
	{ "initialcloaks","0" },
	{ "initialsensors","0" },
	{ "initialwideangles","0" },
	{ "initialrearshots","0" },
	{ "initialafterburners","0" },
	{ "initialtransporters","0" },
	{ "initialmirrors","0" },
	{ "maxarmor","10" },
	{ "initialdeflectors","0" },
	{ "initialhyperjumps","0" },
	{ "initialphasings","0" },
	{ "initiallasers","0" },
	{ "initialemergencythrusts","0" },
	{ "initialtractorbeams","0" },
	{ "initialautopilots","0" },
	{ "initialemergencyshields","0" },
	{ "maxfuel","10000" },
	{ "maxtanks","8" },
	{ "maxecms","10" },
	{ "maxmines","10" },
	{ "maxmissiles","10" },
	{ "maxcloaks","10" },
	{ "maxsensors","10" },
	{ "maxwideangles","10" },
	{ "maxrearshots","10" },
	{ "maxafterburners","10" },
	{ "maxtransporters","10" },
	{ "maxdeflectors","10" },
	{ "maxphasings","10" },
	{ "maxhyperjumps","10" },
	{ "maxemergencythrusts","10" },
	{ "maxlasers","5" },
	{ "maxtractorbeams","4" },
	{ "maxautopilots","10" },
	{ "maxemergencyshields","10" },
	{ "maxmirrors","10" },
	{ "gameduration","0.0" },
	{ "allowviewing","no" },
	{ "friction","0.0" },
	{ "checkpointradius","6.0" },
	{ "racelaps","3" },
	{ "lockotherteam","yes" },
	{ "loseitemdestroys","no" },
	{ "usewreckage","yes"},
	{ "maxoffensiveitems","100" },
	{ "maxdefensiveitems","100" },
	{ "rounddelay","0" },
	{ "maxroundtime","0" },
	{ "numberofrounds","0" },
	{ "analyticalcollisiondetection", "yes" },
	{ "plockserver","no" },
	{ "timerresolution","0" },
	{ "password","\0" }
};
